FROM lukasheinrich/athena_trfsbase
ADD submit.sh /code/resources/submit.sh
ADD writejobjson.py /code/resources/writejobjson.py
ADD status.sh /code/resources/status.sh
ADD getstatus.py /code/resources/getstatus.py
