FROM hepsw/cvmfs-atlas
RUN yum groupinstall -y "Development Tools"
RUN yum install -y git make gcc-c++ gcc binutils libX11-devel libXpm-devel libXft-devel libXext-devel
RUN yum install -y gcc-gfortran openssl-devel pcre-devel mesa-libGL-devel glew-devel ftgl-devel mysql-devel fftw-devel cfitsio-devel graphviz-devel avahi-compat-libdns_sd-devel libldap-dev python-devel libxml2-devel gsl-static
RUN yum install -y procmail openssl098e.x86_64 compat-libf2c-34.x86_64 libtool-ltdl libtool-ltdl-devel
